<h1>Index<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Usage" data-toc-modified-id="Usage-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Usage</a></span><ul class="toc-item"><li><span><a href="#linspace" data-toc-modified-id="linspace-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span><em>linspace</em></a></span></li><li><span><a href="#Min-and-Max" data-toc-modified-id="Min-and-Max-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Min and Max</a></span></li><li><span><a href="#Other-functions" data-toc-modified-id="Other-functions-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Other functions</a></span></li><li><span><a href="#Creating-arrays-by-using-lists" data-toc-modified-id="Creating-arrays-by-using-lists-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Creating arrays by using lists</a></span></li><li><span><a href="#Accessing-and-changing-elements" data-toc-modified-id="Accessing-and-changing-elements-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Accessing and changing elements</a></span></li><li><span><a href="#random" data-toc-modified-id="random-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span><em>random</em></a></span></li><li><span><a href="#Constants" data-toc-modified-id="Constants-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Constants</a></span></li><li><span><a href="#Arrays-multiplication" data-toc-modified-id="Arrays-multiplication-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Arrays multiplication</a></span></li></ul></li><li><span><a href="#Excercise" data-toc-modified-id="Excercise-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Excercise</a></span></li></ul></div>

# Introduction

Numpy is a package for high efficiency numerical operations. A huge part of Python's scientific packages are built on numpy. Instead of using lists with numbers and for loops to operate on those lists, you can use *numpy arrays* to do the same more easily, and faster. Numpy is the package most similar to Matlab programming.

# Usage

It is common to import numpy and abbreviate it as **np**.

In [1]:
import numpy as np

If you need to find something in numpy you can use the function **lookfor**.

In [2]:
np.lookfor('sin')

Search results for 'sin'
------------------------
numpy.sin
    Trigonometric sine, element-wise.
numpy.sinc
    Return the sinc function.
numpy.sinh
    Hyperbolic sine, element-wise.
numpy.isinf
    Test element-wise for positive or negative infinity.
numpy.arcsin
    Inverse sine, element-wise.
numpy.arcsinh
    Inverse hyperbolic sine element-wise.
numpy.any
    Test whether any array element along a given axis evaluates to True.
numpy.cos
    Cosine element-wise.
numpy.cosh
    Hyperbolic cosine, element-wise.
numpy.savez
    Save several arrays into a single file in uncompressed ``.npz`` format.
numpy.trapz
    Integrate along the given axis using the composite trapezoidal rule.
numpy.MachAr
    Diagnosing machine parameters.
numpy.arccos
    Trigonometric inverse cosine, element-wise.
numpy.ma.sin
    Trigonometric sine, element-wise.
numpy.kaiser
    Return the Kaiser window.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.nditer
    Ef

## *linspace*

You can create vectors uniformly spaced with linspace and the following syntax:
```Python 
    np.linspace(start,end,step)
```
In this case, star and end points are included in the vector. Example:

In [3]:
x = np.linspace(0, 10, 16)
print(type(x))
print(x)
print(x.shape)

<class 'numpy.ndarray'>
[  0.           0.66666667   1.33333333   2.           2.66666667
   3.33333333   4.           4.66666667   5.33333333   6.           6.66666667
   7.33333333   8.           8.66666667   9.33333333  10.        ]
(16,)


Note that you can see the dimension of the vector with the method **shape**. By default numpy creates arrays with only one dimension. To add an additional dimension you will have to use the method **reshape([dimension1, dimension2])**.

In [4]:
print(x.reshape([1,16]).shape)
print(x.reshape([-1,4]).shape)

(1, 16)
(4, 4)


Note that it is also possible to specify only one dimension and let numpy deduce the other by assigning one dimension as -1. 

Since numpy works with vectors, it is possible to use vector operations:

In [5]:
y1 = x * 2
y2 = np.sin(x)
y3 = x ** 2 - 10 * x + 5

## Min and Max

To find the minimum value and its index we can use **min** and **argmin**. The maximum and maximum index we can use **max** and **argmax**

In [6]:
y3_min = y3.min()
y3_argmin = y3.argmin()

print(y3_min, y3[y3_argmin], y2[y3_argmin], x[y3_argmin])

-19.8888888889 -19.8888888889 -0.998954917098 4.66666666667


## Other functions

Numpy has a lot of fucntions and can do almost the same that Matlab does. A complete list of fucntions can be obtained with **dir**

In [7]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import

## Creating arrays by using lists

You can create arrays by using list with **array** function:

In [8]:
list1 = [1, 2, 3, 4, 5]
array1 = np.array(list1)

list2d = [[1, 2, 3, 4], [5, 6, 7, 8]]
array2d = np.array(list2d)

print(f'{type(array1)}{array1}\n\n{array2d}')
print(np.array([[0,1,0],[1,0,0],[0,0,1]]))

<class 'numpy.ndarray'>[1 2 3 4 5]

[[1 2 3 4]
 [5 6 7 8]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]


## Accessing and changing elements

In 1d arrays you can access to the elements with **array[index]**. In 2d arrays you can access with **array[index1,index2]** or **array[index1][index2]**.

In [9]:
item1 = array2d[0][1]
item2 = array2d[0, 1]
print(item1 == item2)

True


*Slicing* works in the same form as in the lists:

In [10]:
middle = array2d[0:2, 1:3]
middle

array([[2, 3],
       [6, 7]])

It is important to note that the slices in `arrays` return a *reference* to the array, not a copy, as in lists. Therefore, if you change a value of this reference, the original array is changed.

In [11]:
array2d = np.array(list2d)
print('Original:\n', array2d)
middle = array2d[0:2, 1:3]
middle[:, :] = [[0, 0], [0, 0]]
print('Changed:\n', array2d)

Original:
 [[1 2 3 4]
 [5 6 7 8]]
Changed:
 [[1 0 0 4]
 [5 0 0 8]]


To avoid that it is necessary create a copy of the array with  **copy()**

In [12]:
array2d = np.array(list2d)
print('Original:\n', array2d)

middle = array2d[0:2, 1:3].copy()
middle[:, :] = [[0, 0], [0, 0]]

print('Not changed:\n', array2d)

Original:
 [[1 2 3 4]
 [5 6 7 8]]
Not changed:
 [[1 2 3 4]
 [5 6 7 8]]


## *random*

Random is a package inside numpy. The role of random functions is to provide a way to choose a value from a list at random, or to generate random values. Run the following cell several times to see the values change.

In [13]:
r1 = np.random.random()  # random number between 0 and 1
r2 = np.random.choice(array1)  # Chose a random element in a list
r3 = np.random.randint(5)  # random number between 0 and 5

print(f'{r1:.2f}; {r2:.2f}; {r3:.2f}')

0.86; 2.00; 4.00


## Constants

Numpy has some constans included:

In [14]:
print(f'Pi:{np.pi},\ne:{np.e}')

Pi:3.141592653589793,
e:2.718281828459045


## Arrays multiplication

In [15]:
c = np.array([[1, 2], [6, 7]])
d = np.array([[3, 1], [2, 1]])

print('c:\n', c,'\n\nd:\n', d, '\n')

 # Bitwise
print('Bitwise multiplication\n', c * d, '\n')

# Dot product
print('Dot product\n', np.dot(c, d), '\n') 

c:
 [[1 2]
 [6 7]] 

d:
 [[3 1]
 [2 1]] 

Bitwise multiplication
 [[ 3  2]
 [12  7]] 

Dot product
 [[ 7  3]
 [32 13]] 



Numpy is also able to use C/C++/Fortran code to Python to increase the efficiency of its functions. See their website for more information [here](http://www.numpy.org/). You can also see more differences with matlab [here](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html).

# Excercise
Using numpy create the matrix $Z$ and $T$ with $z_p$ and $z_m$ equal to any constant, and a = $e^{j2\pi/3}$. Then do $T^{-1}ZT$ and print the diagonal elements of the result. 

$$
Z = \left[\begin{array}{ccc} 
z_p & z_m & z_m\\
z_m & z_p & z_m\\
z_m & z_m & z_p\\
\end{array}\right]
\quad
T = \left[\begin{array}{ccc} 
1 & 1 & 1\\
1 & a^2 & a\\
1 & a & a^2\\
\end{array}\right]
$$ 

Tips: 
- I am asking for a matrix and not a 2 dimensional array      
- All objects have their own built in methods